#!/bin/sh
cd $(dirname "$0")
SECRET=$(grep 'gb::$secret' ../../../gb-config.php | cut -d' ' -f 3 | sed "s/[;']//g")
git --git-dir=.. --work-tree=../.. log -p --full-index -1 \
| curl \
	-H 'x-gb-shared-secret: '$SECRET \
	--connect-timeout 5 \
	--max-time 30 \
	--silent --show-error \
	--data-binary @- \
	-k \
	$(cat ../info/gitblog-site-url)'gitblog/hooks/post-patch.php'
