#!/bin/sh
cd $(dirname "$0")
SECRET=$(grep 'gb::$secret' ../../gb-config.php | cut -d' ' -f 3 | sed "s/[;']//g")
RSP=$(git --git-dir=.. --work-tree=../.. log -p --full-index -1 \
| curl \
	-H 'X-gb-shared-secret: '$SECRET \
	-H 'Expect:' \
	--connect-timeout 5 \
	--max-time 30 \
	--silent --show-error \
	--data-binary @- \
	-k \
	$(cat ../info/gitblog-site-state|cut -d' ' -f1)'gitblog/hooks/post-patch.php')
echo "$RSP"
if (echo "$RSP" | grep -q -E '^error'); then
	exit 1
fi
